# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = "APP_ENV=dev ./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "frontend"]
  exclude_file = []
  follow_symlink = true
  kill_signal = "INT"
  log = "air.log"
  stop_on_error = true
[log]
  time = true
  main_only = true
